openapi:
  info:
    title: ${OPENAPI_INFO_TITLE:-Application API}
    description: ${OPENAPI_INFO_DESCRIPTION:-description}
    version: ${OPENAPI_INFO_VERSION:-v1.0}
    licence:
      name: ${OPENAPI_INFO_LICENCE_NAME:-Apache 2.0}
      url: ${OPENAPI_INFO_LICENCE_URL:-http://springdoc.org}
    contact:
      name: ${OPENAPI_INFO_CONTACT_NAME:-username}
      email: ${OPENAPI_INFO_CONTACT_EMAIL:-test@gmail.com}
  servers: '${OPENAPI_SERVERS:{"localhost:8080":"Dev server"}}'


security:
  geolocation-api:
    api-key: ${SECURITY_GEOLOCATION_APIKEY}
  email-verification:
    mail-sender-name: Message inc
    subject: Please verify your registration
    confirmation-server-address: http://localhost:8080

  encryption:
    access-token:
      expiration-time: '604800000'
      signing-key: tO8LeGFYHpx5xP0i8SAVqgpvaVwN+rwrqyTlndBAnaZmP6R+a43E+NzDXi36gbm/HAFnl7TCShg90nk4eMA0pXIIiZGAfIqWUporw+k6XR4=
    refresh-token:
      expiration-time: '1209600000'
      signing-key: R+jF202C6JeTuDPZZqjDGpKS9D7PwnQukzlNgwNlmUU4kZ0gtWGiIOXIzFHgxn3QO6UkcZBPtZMBFXXt9qlAUDNTKPfAylG/xRmZh9ghTjg=
    confirmation-token:
      signing-key: PrbGMDXQSlrvFu76M9lpPcWoENIdgCKtrr7ZWqIhR1fm8nPNri182Y4ia3A+aDkoyFr0bEq3wH7gay5Kth6StDDRgrexDn4vX49B7FzTujg=
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  liquibase:
    enabled: ${SPRING_ENABLE_LIQUIBASE:-true}
    drop-first: ${SPRING_ENABLE_LIQUIBASE_DROP_FIRST:-false}
    default-schema: public
  mvc:
    contentnegotiation:
      parameter-name: "format"
      default-type: application/json
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: '587'

server:
  error:
    include-binding-errors: always
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  level:
    org:
      springframework:
        security: TRACE

