openapi:
  info:
    title: ${OPENAPI_INFO_TITLE:-Messenger API}
    description: ${OPENAPI_INFO_DESCRIPTION:-simplified messenger functionality}
    version: ${OPENAPI_INFO_VERSION:-v1.0}
    licence:
      name: ${OPENAPI_INFO_LICENCE_NAME:-Apache 2.0}
      url: ${OPENAPI_INFO_LICENCE_URL:-http://springdoc.org}
    contact:
      name: ${OPENAPI_INFO_CONTACT_NAME:-spyro}
      email: ${OPENAPI_INFO_CONTACT_EMAIL:-al_matjuhin@mail.ru}
  servers: '${OPENAPI_SERVERS:{"localhost:8080":"Dev server"}}'
security:
  email-verification:
    mail-sender-name: Message inc
    confirmation-server-address: http://localhost:8080
  encryption:
    access-token:
      expiration-time: '${SECURITY_ACCESS_TOKEN_EXPIRATION_TIME:-604800000}'
      signing-key: ${SECURITY_ACCESS_TOKEN_SIGNING_KEY}
    refresh-token:
      expiration-time: '${SECURITY_REFRESH_TOKEN_EXPIRATION_TIME:-1209600000}'
      signing-key: ${SECURITY_REFRESH_TOKEN_SIGNING_KEY}
app:
  time-for-account-recovery: '${APP_TIME_FOR_ACCOUNT_RECOVERY:-60000}'
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  liquibase:
    enabled: ${SPRING_ENABLE_LIQUIBASE:-true}
    drop-first: ${SPRING_ENABLE_LIQUIBASE_DROP_FIRST:-false}
    default-schema: public
  mvc:
    contentnegotiation:
      parameter-name: "format"
      default-type: application/json
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: '587'

server:
  error:
    include-binding-errors: always
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  level:
    org:
      springframework:
        security: TRACE

