delete from users;
insert into users(user_id,
                  username,
                  email,
                  password,
                  user_first_name,
                  user_last_name,
                  role,
                  confirmed,
                  activated,
                  messages_allowed_from_friends_only,
                  friends_hidden_from_everyone)
values (1,
        'alex1337rus',
        '1z.zed.z1@gmail.com',
        '$2a$10$oEHjT9GTDCmlAfUiizUAI.svwzQVtwHYvSDNjiRbnLLFvCbZzBuF2',
        'alex',
        'rus',
        'USER',
        true,
        true,
        false,
        false);